<a href="https://colab.research.google.com/github/hyosungHWANG/201927151_hyosung/blob/main/2024_01_09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [68]:
a = np.arange(1,37).reshape(3,3,4) #층,행,열

print(a)
print(a.shape)
print(a.reshape(3,4,3))
print(a.flatten())

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]
(3, 3, 4)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


In [58]:
import numpy as np

a = np.arange(1,26).reshape(5,5)

print(a)
print(a.shape)
print(a[3][3])
print(a[:2,:2])
print(a[3:5,3:5])
print(a[0:2, :])
print(a[:, -2:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
(5, 5)
19
[[1 2]
 [6 7]]
[[19 20]
 [24 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]


In [42]:
import numpy as np

i = 1

while True:
  a = np.arange(i,i+5,1)
  print(a)
  i = i+5
  if i == 21:
    break

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]
[16 17 18 19 20]


In [36]:
import numpy as np
arr1 = np.array([[1,2,3],
[4,5,6],
[7,8,9]])

print(arr1[0])
print(arr1[0,2])
print(arr1[1:])
print(arr1[arr1 > 5])

[1 2 3]
3
[[4 5 6]
 [7 8 9]]
[6 7 8 9]


In [35]:
import numpy as np

arr1 = np.ones([3,4])

print(arr1)
print('size :', arr1.size)
print('dtype :', arr1.dtype)
print('shape :', arr1.shape)
print('ndim :',arr1.ndim)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
size : 12
dtype : float64
shape : (3, 4)
ndim : 2


In [34]:
import numpy as np

a = np.arange(1,10,2)
print(a)

b = np.ones((3,4))
print(b)

c = np.linspace(0,1,10)
print(c)

[1 3 5 7 9]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [23]:
import numpy as np

arr = np.linspace(0, 1, 5) #여기서 5는 생성할 숫자의 수 의미
print(arr)


[0.   0.25 0.5  0.75 1.  ]


In [22]:
import numpy as np

arr_1d = np.random.rand(5)
print(arr_1d)

arr_2d = np.random.rand(2, 3)
print(arr_2d)


[0.13676508 0.31161613 0.38248849 0.96360034 0.50924657]
[[0.97035878 0.44341086 0.38938896]
 [0.02694821 0.73234688 0.66655317]]


In [17]:
import numpy as np

ones_1d = np.ones(5)
print(ones_1d)

ones_2d = np.ones((3, 4))
print(ones_2d)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
import numpy as np

zeros_1d = np.zeros(5)
print(zeros_1d)

zeros_2d = np.zeros((3, 4))
print(zeros_2d)


[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
import numpy as np

arr = np.arange(10)
print(arr)

arr = np.arange(2, 20, 2)
print(arr)


[0 1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16 18]


In [14]:
import numpy as np

lst = [1, 2, 3]
arr = np.array(lst)

print(type(lst),lst)
print(type(arr),arr)

<class 'list'> [1, 2, 3]
<class 'numpy.ndarray'> [1 2 3]


In [13]:
import numpy as np

arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d)

arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)

print("Shape:", arr2d.shape)
print("Dimensions:", arr2d.ndim)
print("Data Type:", arr2d.dtype)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2
Data Type: int64


In [12]:
import numpy as np

In [6]:
a = input()
sum = 0

for i in a:
  sum = sum + int(i)

print(sum)

700000000001
8
